### ISSUE TITLE
Customized build still shows 4.3.0 version in main.css file.

### ISSUE THREAD

**Issue by sandrodz** [h5bp/html5-boilerplate#1672]
Customized build still shows 4.3.0 version in main.css file.

**Comment by alrra** [comment]
> Customized build still shows 4.3.0 version in main.css file.

@sandrodz Can you be more specific?  I see [`v5.0.0`](https://github.com/h5bp/html5-boilerplate/blob/60a8ff033665e1207714d6670fcd7b65304ec02f/dist/css/main.css#L1)

**Comment by sandrodz** [comment]
http://www.initializr.com/ -> classic. At the top of main.css it states 4.3.0. Though css is completely different, which I suppose is already version 5.0.0

**Comment by alrra** [comment]
@sanand0 Please open an issue in the [initializr-website](https://github.com/verekia/initializr-website) repository. Thanks!

Cc: @verekia.

**Comment by alrra** [comment]
@sandrodz Please open an issue in the [initializr](https://github.com/verekia/initializr) repository. Thanks!

Cc: @verekia.

**Comment by verekia** [comment]
FYI, this is fixed.

**Comment by arthurvr** [comment]
Thanks, @verekia!

**Comment by sandrodz** [comment]
Is it in production? I just downloaded it and still shows 4.3.

**Comment by verekia** [comment]
Yes, give it some time to propagate :)

**Comment by sandrodz** [comment]
css wise there was no discrepancy correct? That is indeed v 5.0.0 css I'm seeing there?

**Comment by patrickkettner** [comment]
[yes](https://github.com/verekia/initializr/commit/ac535f34d66411d99718be892290ee62199968ba)

**Comment by sandrodz** [comment]
awesome! thx.
